format = """$kubernetes$aws$line_break$nix_shell$time$git_branch$git_status$directory$character"""
right_format = """$all"""
add_newline = false

"$schema" = 'https://starship.rs/config-schema.json'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[➜](bold red)'

[directory]
disabled = false

[aws]
disabled = false
format = '\[[$symbol ($profile )(\($region\))(\[$duration\])]($style)\] '
style = 'bold green'
symbol = ' '
[aws.region_aliases]
us-east-1 = 'va'
eu-west-2 = 'london'
eu-west-1 = 'ireland'

[kubernetes]
disabled = false
symbol = '󱃾'
style = 'bold blue'
format = '\[[$symbol $context( \($namespace\))]($style)\] '

[git_branch]
disabled = false
format = '\[[$symbol$branch]($style)\] '

[git_state]
disabled = true
format = '([\[$all_status$ahead_behind\]]($style))'

[git_status]
disabled = false

[golang]
disabled = false
symbol = ''
format = '\[[$symbol ($version)]($style)\] '

[ruby]
disabled = false
format = '\[[$symbol($version)]($style)\] '

[nix_shell]
disabled = false
symbol = "󱄅"
format = '\[[$symbol]($style)\]'

[docker_context]
disabled = false
format = '\[[$symbol$context]($style)\] '

[terraform]
disabled = false
symbol = '󱁢'
format = '[$symbol $version $workspace]($style) '

[time]
disabled = false
format = '[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = 'local'

[gcloud]
disabled = true
